services:
  mariadb:
    image: mariadb:10.11
    container_name: some_mariadb
    ports:
      - "3306:3306"
    environment:
      MARIADB_USER: chris
      MARIADB_PASSWORD: 123456
      MARIADB_DATABASE: simulate
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: "1"
    volumes:
      - /home/chris/data_store:/var/lib/mysql
    restart: always
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      retries: 5
      start_period: 5s

  redis:
    image: redis:4.0.2-alpine
    container_name: some_redis
    expose:
      - "6379:6379"

  php-fpm:
    image: phalcon:v3.4.5
    container_name: some_php_fpm
    depends_on:
      mariadb:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - /home/chris/phalcon_starter/work:/var/www/html
    expose:
      - "9000"

  nginx:
    image: nginx:alpine
    container_name: some_nginx
    depends_on:
      php-fpm:
        condition: service_started
    ports:
      - "80:80"
    volumes:
      - /home/chris/phalcon_starter/etc/nginx/conf.d:/etc/nginx/conf.d
      - /home/chris/phalcon_starter/work:/var/www/html
