services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - /mnt/d/History/Git/learn-phalcon/3.4/docker/etc/nginx/conf.d:/etc/nginx/conf.d
      - /mnt/d/History/Git/learn-phalcon/3.4/docker/work:/var/www/html
    depends_on:
      - php-fpm

  php-fpm:
    image: phalcon:v3.4.5
    volumes:
      - /mnt/d/History/Git/learn-phalcon/3.4/docker/work:/var/www/html
    expose:
      - "9000"